const en = {
  signin_title: 'Sign in',
  signin_submitButton: 'Sign in',
  signin_dhacc: "Don't have an account?",
  signin_signup: 'Create one',
  signin_placeholderEmail: 'Type your E-mail',
  signin_placeholderPassword: 'Type your password',
  signinError_invalidFields: 'Incorrect E-mail or password',
  signinError_invalidUser: "User doesn't exists",
  signinError_anotherError: 'Error logging in (System)',
  signinError_allFields: 'Fill in all fields!',

  signup_title: 'Create account',
  signup_user: 'User',
  signup_cpassword: 'Confirm password',
  signup_submitButton: 'Sign up',
  signup_placeholderUser: 'Choose a username',
  signup_placeholderEmail: 'Type your E-mail',
  signup_placeholderPassword: 'Create your password',
  signup_placeholderCPassword: 'Confirm your password',
  signupError_invalidUser: 'User already exists',
  signupError_invalidEmail: 'E-mail already registered',
  signupError_anotherError: 'Error while registering user',
  signupError_allFields: 'Fill in all fields!',

  config_title: 'Languages',
  config_ptBr: 'Portuguese (BR)',
  config_en: 'English (EN)',
  config_es: 'Spanish (ES)',

  dashboard_title: 'Dashboard',
  dashboard_systemTitle: 'System',
  dashboard_totalUsers: 'Total Users',
  dashboard_totalMatches: 'Total Matches',
  dashboard_userTitle: 'User',
  dashboard_createdMatches: 'Created Matches',
  dashboard_finishedMatches: 'Finalized Matches',

  teams_title: 'Teams',
  team_title: 'Team',
  team_currentTeam: 'Current Roster',

  createMatch_title: 'Create Match',
  createMatch_map: 'Select Map',
  createMatch_date: 'Date',
  createMatch_time: 'Time',
  createMatch_firstTeam: 'Team 1',
  createMatch_secondTeam: 'Team 2',
  createMatch_submitButton: 'Publish',
  createMatch_selectItem: 'Select an item',
  createMatch_matchFinished: 'Match Finalized',
  createMatch_matchPoints: 'Match Score',
  createMatchError_differentTeams: 'Select different teams!',

  matchesResults_title: 'Results',
  matchesResults_team: 'Team',
  matchesResults_time: 'Time',
  matchesResults_selectMap: 'Select a map',

  match_title: 'Match',
  match_players: 'Players',
  match_matchTitle: 'Campeonato Brasileiro',
  match_kill: 'K',
  match_death: 'D',
  match_assists: 'A',

  menuItem_teams: 'Teams',
  menuItem_dashboard: 'Dashboard',
  menuItem_languages: 'Languages',
  menuItem_createMatch: 'Create Match',
  menuItem_finishedMatches: 'Finished Matches',
  menuItem_upcomingMatches: 'Upcoming Matches',
  menuItem_exit: 'Exit',

  menuTitle_teams: 'Teams',
  menuTitle_dashboard: 'Dashboard',
  menuTitle_languages: 'Language Settings',
  menuTitle_createMatch: 'Create Match',
  menuTitle_finishedMatches: 'Finished Matches',
  menuTitle_upcomingMatches: 'Upcoming Matches',

  password: 'Password',
  noResults: 'No results',
};

export default en;
