const es = {
  signin_title: 'Iniciar sesión',
  signin_submitButton: 'Entrar',
  signin_dhacc: '¿No tienes una cuenta?',
  signin_signup: 'Registro',
  signinError_invalidFields: 'Correo o contraseña incorrectos',
  signinError_invalidUser: 'Usuario no registrado',
  signinError_anotherError: 'Error al iniciar sesión (Sistema)',
  signinError_allFields: '¡Rellena todos los campos!',
  signin_placeholderEmail: 'Escribe tu E-mail',
  signin_placeholderPassword: 'Escribe tu contraseña',

  signup_title: 'Crear cuenta',
  signup_user: 'Usuario',
  signup_cpassword: 'Confirmar contraseña',
  signup_submitButton: 'Registrar',
  signupError_invalidUser: 'nombre de usuario ya existe',
  signupError_invalidEmail: 'Correo electrónico ya registrado',
  signupError_anotherError: 'Error al registrar usuario',
  signupError_allFields: '¡Rellena todos los campos!',
  signup_placeholderUser: 'Elige un nombre de usuario',
  signup_placeholderEmail: 'Escribe tu E-mail',
  signup_placeholderPassword: 'Crea tu contraseña',
  signup_placeholderCPassword: 'Ingresa tu contraseña nuevamente',

  config_title: 'Idiomas',
  config_ptBr: 'Portugués (BR)',
  config_en: 'Inglés (EN)',
  config_es: 'Español (ES)',

  dashboard_title: 'Panel',
  dashboard_systemTitle: 'Sistema',
  dashboard_totalUsers: 'Usuarios Totales',
  dashboard_totalMatches: 'Partidos totales',
  dashboard_userTitle: 'Usuario',
  dashboard_createdMatches: 'Partidos Creadas',
  dashboard_finishedMatches: 'Partidos Terminados',

  teams_title: 'Equipos',
  team_title: 'Equipo',
  team_currentTeam: 'Equipo Actual',

  createMatch_title: 'Crear Partido',
  createMatch_map: 'seleccione el mapa',
  createMatch_date: 'Fecha',
  createMatch_time: 'Tiempo',
  createMatch_firstTeam: 'Equipo 1',
  createMatch_secondTeam: 'Equipo 2',
  createMatch_submitButton: 'Publicar',
  createMatch_selectItem: 'Selecciona un artículo',
  createMatch_matchFinished: 'Partido terminado',
  createMatch_matchPoints: 'Pontuación del Partido',
  createMatchError_differentTeams: '¡Selecciona diferentes equipos!',

  matchesResults_title: 'Resultados',
  matchesResults_team: 'Equipo',
  matchesResults_time: 'Tiempo',
  matchesResults_selectMap: 'Seleccione un mapa',

  match_title: 'Partido',
  match_players: 'Jugadores',
  match_matchTitle: 'Campeonato Brasileiro',
  match_kill: 'E',
  match_death: 'M',
  match_assists: 'A',

  menuItem_teams: 'Equipos',
  menuItem_dashboard: 'Panel',
  menuItem_languages: 'Idiomas',
  menuItem_createMatch: 'Crear partido',
  menuItem_finishedMatches: 'Partidos terminados',
  menuItem_upcomingMatches: 'Próximos juegos',
  menuItem_exit: 'Salir',

  menuTitle_teams: 'Equipos',
  menuTitle_dashboard: 'Panel',
  menuTitle_languages: 'Ajustes de idioma',
  menuTitle_createMatch: 'Crear partido',
  menuTitle_finishedMatches: 'Partidos terminados',
  menuTitle_upcomingMatches: 'Próximos juegos',

  password: 'Contraseña',
  noResults: 'No hay resultados',
};

export default es;
